server.port=8080
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DATABASE_NAME}?sslmode=require
spring.datasource.username=${USER_DB}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Manual approval for production
app.auto-approve-restaurants=false
app.auto-approve-foods=false

# JWT
jwt.SecretKey=${JWT_SECRET_KEY}

# Frontend URL
frontend.url=${FRONTEND_URL}

# mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8

spring.mail.test-connection=false

admin.email=${ADMIN_EMAIL}

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

groq.api.key=${GROQ_API}
# Google Maps
google.maps.api.key=${GOOGLE_MAPS_API_KEY}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false


springdoc.show-actuator=false